[general]
live_config_reload = true

[window]
dynamic_padding = false
startup_mode = "Maximized"
decorations = "None"

[window.padding]
x = 10
y = 10

[keyboard]
bindings = [
  { key = "Back", mods = "Command", chars = "\u0015" },     # command + delete to delete an entire line
  { key = "Left", mods = "Alt", chars = "\u001Bb" },        # option + left to move cursor one word left
  { key = "Right", mods = "Alt", chars = "\u001Bf" }        # option + right to move cursor one word right
]

[font]
size = 14

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

# Colors (Dracula)

# Default colors
[colors.primary]
background = '#282a36'
foreground = '#f8f8f2'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#ff5555'
green   = '#50fa7b'
yellow  = '#f1fa8c'
blue    = '#bd93f9'
magenta = '#ff79c6'
cyan    = '#8be9fd'
white   = '#bbbbbb'

# Bright colors
[colors.bright]
black   = '#555555'
red     = '#ff5555'
green   = '#50fa7b'
yellow  = '#f1fa8c'
blue    = '#caa9fa'
magenta = '#ff79c6'
cyan    = '#8be9fd'
white   = '#ffffff'