[general]
live_config_reload = true

[window]
dynamic_padding = false
startup_mode = "Maximized"
decorations = "None"

[window.padding]
x = 10
y = 10

[terminal.shell]
program = "pwsh.exe"
args = ["-NoLogo"]

[keyboard]
bindings = [
  { key = "Back", mods = "Control", chars = "\u0017" }     # Ctrl + Backspace to delete an entire word
]

[font]
size = 11

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

# Colors (Dracula)

# Default colors
[colors.primary]
background = '#282a36'
foreground = '#f8f8f2'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#ff5555'
green   = '#50fa7b'
yellow  = '#f1fa8c'
blue    = '#bd93f9'
magenta = '#ff79c6'
cyan    = '#8be9fd'
white   = '#bbbbbb'

# Bright colors
[colors.bright]
black   = '#555555'
red     = '#ff5555'
green   = '#50fa7b'
yellow  = '#f1fa8c'
blue    = '#caa9fa'
magenta = '#ff79c6'
cyan    = '#8be9fd'
white   = '#ffffff'