"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """$directory$git_branch$character"""

[directory]
truncation_length = 0      # Shows up to 3 parent folders before shortening
truncate_to_repo = false    # If inside a git repo, always show the repo root name

[git_branch]
format = "| [$branch]($style) "